### ISSUE TITLE
Help with GitHub.js

### ISSUE THREAD

**Issue by amaralDaniel** [prose/gatekeeper#56]
Hi there! I'm not fully understanding how to use Gatekeeper and github.js to provide OAuth authentication. Can anyone provide some thought or resource that can help to achieve it? I searched around and nothing insightful comes up.

**Comment by dereklieu** [comment]
Hey, there are some notes in #54. Github's own Oauth docs are probably the best starting point. Gatekeeper follows the web flow linked in that ticket. I'm sorry, I would love Gatekeeper to be an out-of-the-box solution for people who don't know anything about Oauth, but it's currently not set up for that, and you'll have to do some more homework.

Also pointing out that there's no github.js client library, instead of we use the Github API which provides access tokens.

**Comment by amaralDaniel** [comment]
I am considering github.js since it says in the Gatekeeper description. Is it cool to use it?

**Comment by dereklieu** [comment]
Oh you mean this [github.js](https://github.com/github-tools/github). Yeah it's cool, but not required to use with Gatekeeper, which just handles Oauth.

**Comment by amaralDaniel** [comment]
So I can handle Oauth with github.js alone?

**Comment by danielo515** [comment]
> So I can handle Oauth with github.js alone?

No you can't. You can use github.js to access public information of repositories. If the user provides you a token then you can have full access to all github features that token provides.
If the user does not provide you with a token you will have to get one yourself, which is what gatekeeper is for. Github does not allow oauth flow to be executed from client side code (web app) and because that reason and for easing the process gatekeeper born.
